# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_deliverto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.Items')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='del_add',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='del_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='del_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='del_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.DeliverTo'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='del_pin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='del_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='pickup_add',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='pickup_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='pickup_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='pickup_pin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='pickup_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='total_fare',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='order_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order_info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.OrderInfo'),
        ),
    ]
