# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_auto_20170603_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='quantity',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
